# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6

    - name: Setup Chrome
      # You may pin to the exact commit or the version.
      # uses: browser-actions/setup-chrome@facf10a55b9caf92e0cc749b4f82bf8220989148
      uses: browser-actions/setup-chrome@v1.7.2
      
      with:
        # The Google Chrome/Chromium version to install and use.
        chrome-version: # optional, default is latest
        # Install dependent packages for Google Chrome/Chromium (Linux only).
        install-dependencies: # optional
        # Install the compatible version of ChromeDriver with the installed Google Chrome/Chromium.
        install-chromedriver: # optional
        # Do not use sudo to install Google Chrome/Chromium (Linux only).
        no-sudo: # optional
            
